<?php

function dna_menu() {
  $items = array();
  $items['dna'] = array(
    'title' => 'Double Helix Mirror',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dna_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['dna_results_page'] = array(
    'title' => 'Results',
    'page callback' => 'dna_results',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;

}

function dna_form() {
  $form = array();
  $form['dna_first_half'] = array(
    '#title' => 'First half of the double helix',
    '#type' => 'textfield',
    '#description' => t('Please enter your DNA helix.'),
    '#element_validate' => array('element_validate_letter'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Calculate DNA',
  );

  return $form;
}

//form validation to check that the correct type of inputs are entered.
function element_validate_letter($form, &$form_state) {
  $split_letter = str_split(strtoupper($form_state['values']['dna_first_half']));
  foreach($split_letter as $letter) {
    if ($letter != "A" &&
        $letter != "T" &&
        $letter != "C" &&
        $letter != "G" &&
        $letter != " " ) {
      form_set_error('dna_first_half', 'Must enter a string of valid DNA Helix values (A, T, C, or G)');
    };
  };
}

//this creates the mirror image of the string
function calculate_dna($pretty_input) {
  $mirror_letter = "";
  $result_array = array();

  foreach($pretty_input as $letter) {
    if ($letter == "A") {
      $mirror_letter = "T";
    } elseif ($letter == "T") {
      $mirror_letter = "A";
    } elseif ($letter == "C") {
      $mirror_letter = "G";
    } elseif ($letter == "G") {
      $mirror_letter = "C";
    } elseif ($letter == "") {
      $mirror_letter = "";
    }
    array_push($result_array, $mirror_letter);
  }
  return $result_array;
}

//this takes the original string, removing spaces and capitalizes each character.
function pretty_dna($input) {
  $pretty_dna_array = array();
  $split_letter = str_split(strtoupper($input));

  foreach($split_letter as $letter) {
    if ($letter == " ") {
      $letter = "";
    }
    array_push($pretty_dna_array, $letter);
  }
  return $pretty_dna_array;
}

function dna_form_submit($form, &$form_state) {
  $dna_input = $form_state['values']['dna_first_half'];
  //first clean up the original string using the pretty_dna() function
  $pretty_dna_input = pretty_dna($dna_input);
  //second calculate the mirror image of the now "pretty" array of letters
  $dna_output = calculate_dna($pretty_dna_input);

  $_SESSION['dna_view'] = $pretty_dna_input;
  $_SESSION['dna_mirror_view'] = $dna_output;
  $form_state['redirect'] = 'dna_results_page';
}

function dna_results() {
  $original = '';
  $output = '';
  //pull out the letters from both arrays and add them to a string to be returned
  foreach ($_SESSION['dna_view'] as $original_value) {
    $original = $original . $original_value;
  }
  foreach ($_SESSION['dna_mirror_view'] as $value) {
    $output = $output . $value;
  }

  return "The results are in: $original $output";
}
