<?php
/**
 * @file
 * homebrew.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function homebrew_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-homebrew-field_brew_instructions'.
  $field_instances['node-homebrew-field_brew_instructions'] = array(
    'bundle' => 'homebrew',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Detailed brew instructions',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_brew_instructions',
    'label' => 'Brew Instructions',
    'required' => 0,
    'settings' => array(
      'display_summary' => 0,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 5,
    ),
  );

  // Exported field_instance: 'node-homebrew-field_fermentables'.
  $field_instances['node-homebrew-field_fermentables'] = array(
    'bundle' => 'homebrew',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter your fermentables like malts, extracts, and grains.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_fermentables',
    'label' => 'Fermentables',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 2,
    ),
  );

  // Exported field_instance: 'node-homebrew-field_hops'.
  $field_instances['node-homebrew-field_hops'] = array(
    'bundle' => 'homebrew',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Enter your hops!',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_hops',
    'label' => 'Hops',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'node-homebrew-field_notes'.
  $field_instances['node-homebrew-field_notes'] = array(
    'bundle' => 'homebrew',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Add any other details',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 5,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_notes',
    'label' => 'Notes',
    'required' => 1,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'node-homebrew-field_style'.
  $field_instances['node-homebrew-field_style'] = array(
    'bundle' => 'homebrew',
    'default_value' => array(
      0 => array(
        'value' => 'IPA',
      ),
    ),
    'deleted' => 0,
    'description' => 'Add the style of beer',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_style',
    'label' => 'Style',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(),
      'type' => 'options_select',
      'weight' => 1,
    ),
  );

  // Exported field_instance: 'node-homebrew-field_yeasts'.
  $field_instances['node-homebrew-field_yeasts'] = array(
    'bundle' => 'homebrew',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_yeasts',
    'label' => 'Yeasts',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Add any other details');
  t('Add the style of beer');
  t('Brew Instructions');
  t('Detailed brew instructions');
  t('Enter your fermentables like malts, extracts, and grains.');
  t('Enter your hops!');
  t('Fermentables');
  t('Hops');
  t('Notes');
  t('Style');
  t('Yeasts');

  return $field_instances;
}
